# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tFuel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tFuel
pod 'GradientButtonSwift'
pod 'IQKeyboardManagerSwift'
pod 'FittedSheets'

  target 'tFuelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tFuelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
